name: MadGuide
favicon: null
layout_spectrum: 0.94541
typography_spectrum: 0.457917463965714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0b09'
    - '#fffffd'
    - '#2d3235'
    - '#988a7f'
    - '#4a6077'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.7721389112994075
purpose: []
