name: MadGuide
favicon: null
layout_spectrum: 0.94541
typography_spectrum: 0.457917463965714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefffd'
    - '#0a0404'
    - '#c3c7ca'
    - '#34424b'
    - '#72889f'
  brandStrength: 0.17250169441103935
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.7721389112994075
purpose: []
